name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [16.17.0]
        mongodb-version: ['4.4']

    runs-on: ubuntu-latest
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: te

      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm i -g typescript@4.7.4
      - run: npm run build